deepspeed --include localhost:0 --master_port 9090 ./LLaMA-Factory/src/train_bash.py \
    --deepspeed ./configs/ds_config_zero2.json \
    --stage sft \
    --model_name_or_path Qwen/Qwen-14B \
    --use_fast_tokenizer True \
    --do_train \
    --dataset_dir ./data/dataset \
    --dataset tulu_merge \
    --template default \
    --cutoff_len 2048 \
    --finetuning_type lora \
    --lora_rank 64 \
    --lora_target "c_attn","c_proj" \
    --output_dir ./output/tulu_merge \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 2 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 2000 \
    --learning_rate 5e-5 \
    --num_train_epochs 1.0 \
    --plot_loss \
    --fp16 \
    --overwrite_output_dir