tokenizer_configs:

  - name: neurips/qwen_14b
    tokenizer_spec:
      class_name: "helm.proxy.clients.http_model_client.HTTPModelClient"
      args: {
        base_url: "http://localhost:8080"
      }

  - name: neurips/llama2_13b_merge
    tokenizer_spec:
      class_name: "helm.proxy.clients.http_model_client.HTTPModelClient"
      args: {
        base_url: "http://localhost:8080"
      }

  - name: neurips/qwen_14b_merge
    tokenizer_spec:
      class_name: "helm.proxy.clients.http_model_client.HTTPModelClient"
      args: {
        base_url: "http://localhost:8080"
      }